title: My GitHub Pages Blog
author: Darren Xu
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my Github Blog.  This blog will be used to communicate problems I’ve encountered, report clever solutions and act as a reference point for myself and others in the future.

# social links
github_username:  DarrenXu94

show_excerpts: true # set to false to remove excerpts on the homepage
theme: architect
baseurl: /github-pages-with-jekyll
